<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2014-08-31 16:55:44
 */
return [
    'app\\assets\\AllAsset' => [
        'basePath' => 'D:\\xampp\\htdocs\\yii2-basic\\web',
        'js' => [
            'js/all-d0903fc63664b689947e6f6878c83abc.js',
        ],
        'css' => [
            'css/all-ea8a0ffc4d571654d80f84bf3490da07.css',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\bootstrap\\BootstrapPluginAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\FontAwesomeAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\FontRobotoAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\FontOpenSansAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\modules\\main\\assets\\AppAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
];