<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2014-08-29 22:34:37
 */
return [
    'app\\assets\\AllAsset' => [
        'basePath' => 'D:\\Webserver\\apache\\htdocs\\yii2-basic\\web',
        'js' => [
            'js/all-55ff8eb3f0d2a10919eed7613151b69c.js',
        ],
        'css' => [
            'css/all-b8a65e7be4bad29fad3bafc2c0d6f99e.css',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\FontAwesomeAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\FontRobotoAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\FontOpenSansAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\modules\\main\\assets\\AppAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
];