<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2014-08-31 16:07:26
 */
return [
    'app\\assets\\AllAsset' => [
        'basePath' => 'D:\\xampp\\htdocs\\yii2-basic\\web',
        'js' => [
            'js/all-55ff8eb3f0d2a10919eed7613151b69c.js',
        ],
        'css' => [
            'css/all-0b36a504ec6bf5419b8a0215cec07112.css',
        ],
    ],
    'yii\\web\\JqueryAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'yii\\bootstrap\\BootstrapAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\FontAwesomeAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\FontRobotoAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\assets\\FontOpenSansAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
    'app\\modules\\main\\assets\\AppAsset' => [
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AllAsset',
        ],
    ],
];